"use client";
import { useState, useTransition } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
import { Plus, X, Zap, Filter, Trash2 } from "lucide-react";
import { TIPO_EVENTO_LABELS, TIPO_EVENTO_CORES, EMOCOES, DOMINIO_LABELS, cn } from "@/lib/utils";
import { Evento, EventoTipo, DominioEvolutivo } from "@/types";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";
const TIPOS: EventoTipo[] = ["emocional","social","cognitivo","operacional","biologico","financeiro"];
const DOMINIOS: DominioEvolutivo[] = ["cientifico","estrategico","fisico","social","criativo"];
interface ProjetoSimples { id:string; nome:string; cor?:string|null; }
export default function EventosClient({ eventos, projetos }: { eventos:Evento[]; projetos:ProjetoSimples[]; }) {
  const [showForm,setShowForm]=useState(false); const [filtroTipo,setFiltroTipo]=useState<EventoTipo|"">("");
  const [loading,setLoading]=useState(false); const [,startTransition]=useTransition();
  const router=useRouter(); const supabase=createClient();
  const [form,setForm]=useState({ titulo:"",descricao:"",tipo:"emocional" as EventoTipo,emocao:"",energia:5,local:"",projeto_id:"",dominio:"" as DominioEvolutivo|"" });
  const eventosFiltrados=filtroTipo?eventos.filter(e=>e.tipo===filtroTipo):eventos;
  function resetForm(){setForm({titulo:"",descricao:"",tipo:"emocional",emocao:"",energia:5,local:"",projeto_id:"",dominio:""});setShowForm(false);}
  async function handleCreate(e:React.FormEvent){e.preventDefault();setLoading(true);const {data:{user}}=await supabase.auth.getUser();await supabase.from("eventos").insert({...form,user_id:user!.id,dominio:form.dominio||null,projeto_id:form.projeto_id||null,emocao:form.emocao||null,local:form.local||null,descricao:form.descricao||null});resetForm();startTransition(()=>router.refresh());setLoading(false);}
  async function handleDelete(id:string){await supabase.from("eventos").delete().eq("id",id);startTransition(()=>router.refresh());}
  return (
    <div className="p-4 md:p-8 max-w-3xl mx-auto page-enter">
      <div className="flex items-center justify-between mb-6"><div><h1 className="text-xl font-bold text-white flex items-center gap-2"><Zap size={18} className="text-darwin-400"/>Eventos</h1><p className="text-zinc-500 text-sm mt-0.5">{eventos.length} registros</p></div><button onClick={()=>setShowForm(true)} className="btn-primary flex items-center gap-1.5"><Plus size={15}/>Novo evento</button></div>
      <div className="flex items-center gap-2 mb-5 flex-wrap"><Filter size={13} className="text-zinc-600"/>
        <button onClick={()=>setFiltroTipo("")} className={cn("badge border cursor-pointer text-xs px-2.5 py-1",filtroTipo===""?"bg-darwin-600/20 text-darwin-300 border-darwin-500/30":"bg-transparent text-zinc-600 border-zinc-700")}>Todos</button>
        {TIPOS.map(t=>(<button key={t} onClick={()=>setFiltroTipo(filtroTipo===t?"":t)} className={cn("badge border cursor-pointer text-xs px-2.5 py-1",filtroTipo===t?TIPO_EVENTO_CORES[t]:"bg-transparent text-zinc-600 border-zinc-700")}>{TIPO_EVENTO_LABELS[t]}</button>))}
      </div>
      <div className="space-y-2">
        {eventosFiltrados.length===0&&<div className="card p-10 text-center"><Zap size={32} className="text-zinc-700 mx-auto mb-3"/><p className="text-zinc-500">Nenhum evento encontrado.</p><button onClick={()=>setShowForm(true)} className="btn-primary mt-4 inline-flex items-center gap-1.5"><Plus size={14}/>Registrar evento</button></div>}
        {eventosFiltrados.map(ev=>{const projeto=projetos.find(p=>p.id===ev.projeto_id);return(<div key={ev.id} className="card-hover p-4 group"><div className="flex items-start gap-3"><div className="w-1.5 h-1.5 rounded-full bg-darwin-500 mt-2 flex-shrink-0"/><div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-2"><p className="text-sm font-medium text-zinc-200">{ev.titulo}</p><button onClick={()=>handleDelete(ev.id)} className="opacity-0 group-hover:opacity-100 text-zinc-700 hover:text-rose-400 transition-all flex-shrink-0"><Trash2 size={13}/></button></div>{ev.descricao&&<p className="text-xs text-zinc-600 mt-0.5 line-clamp-2">{ev.descricao}</p>}<div className="flex items-center gap-2 flex-wrap mt-2"><span className={cn("badge text-xs",TIPO_EVENTO_CORES[ev.tipo])}>{TIPO_EVENTO_LABELS[ev.tipo]}</span>{ev.emocao&&<span className="text-xs text-zinc-600 bg-zinc-800/50 px-2 py-0.5 rounded-full">{ev.emocao}</span>}{ev.energia!==undefined&&<span className="text-xs text-zinc-600">⚡ {ev.energia}/10</span>}{projeto&&<span className="flex items-center gap-1 text-xs text-zinc-600"><span className="w-1.5 h-1.5 rounded-full inline-block" style={{backgroundColor:projeto.cor??"#6371f2"}}/>{projeto.nome}</span>}<span className="text-xs text-zinc-700 ml-auto">{format(new Date(ev.created_at),"dd MMM, HH:mm",{locale:ptBR})}</span></div></div></div></div>);})}
      </div>
      {showForm&&(<div className="fixed inset-0 z-50 flex items-end md:items-center justify-center p-4 bg-black/60 backdrop-blur-sm"><div className="card w-full max-w-lg max-h-[90vh] overflow-y-auto animate-slide-up"><div className="flex items-center justify-between p-5 border-b border-[rgba(99,113,242,0.1)]"><h2 className="text-sm font-semibold text-white">Novo evento</h2><button onClick={resetForm} className="btn-ghost p-1"><X size={16}/></button></div><form onSubmit={handleCreate} className="p-5 space-y-4"><div><label className="label">Título *</label><input className="input" placeholder="O que aconteceu?" required value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/></div><div><label className="label">Descrição</label><textarea className="input min-h-[80px] resize-none" placeholder="Descreva o contexto..." value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Tipo *</label><select className="select" value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value as EventoTipo})}>{TIPOS.map(t=><option key={t} value={t}>{TIPO_EVENTO_LABELS[t]}</option>)}</select></div><div><label className="label">Emoção</label><select className="select" value={form.emocao} onChange={e=>setForm({...form,emocao:e.target.value})}><option value="">Selecione...</option>{EMOCOES.map(em=><option key={em} value={em}>{em}</option>)}</select></div></div><div><label className="label">Nível de energia: {form.energia}/10</label><input type="range" min="1" max="10" value={form.energia} onChange={e=>setForm({...form,energia:Number(e.target.value)})} className="w-full accent-darwin-500"/></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Local</label><input className="input" placeholder="Casa, trabalho..." value={form.local} onChange={e=>setForm({...form,local:e.target.value})}/></div><div><label className="label">Domínio</label><select className="select" value={form.dominio} onChange={e=>setForm({...form,dominio:e.target.value as DominioEvolutivo|""})}><option value="">Nenhum</option>{DOMINIOS.map(d=><option key={d} value={d}>{DOMINIO_LABELS[d]}</option>)}</select></div></div>{projetos.length>0&&<div><label className="label">Projeto relacionado</label><select className="select" value={form.projeto_id} onChange={e=>setForm({...form,projeto_id:e.target.value})}><option value="">Nenhum</option>{projetos.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></div>}<div className="flex gap-2 pt-2"><button type="button" onClick={resetForm} className="btn-secondary flex-1">Cancelar</button><button type="submit" disabled={loading} className="btn-primary flex-1 disabled:opacity-50">{loading?"Salvando...":"Registrar"}</button></div></form></div></div>)}
    </div>
  );
}