"use client";
import { useState, useTransition } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
import { Plus, X, FolderKanban, Trash2, Edit2, Check } from "lucide-react";
import { DOMINIO_LABELS, PROJETO_STATUS_LABELS, PROJETO_STATUS_CORES, PROJETO_CORES, cn } from "@/lib/utils";
import { Projeto, ProjetoStatus, DominioEvolutivo } from "@/types";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";
const STATUS_LIST: ProjetoStatus[] = ["ativo","pausado","concluido","arquivado"];
const DOMINIOS: DominioEvolutivo[] = ["cientifico","estrategico","fisico","social","criativo"];
export default function ProjetosClient({ projetos, eventosCount }: { projetos:Projeto[]; eventosCount:Record<string,number>; }) {
  const [showForm,setShowForm]=useState(false); const [editingId,setEditingId]=useState<string|null>(null);
  const [loading,setLoading]=useState(false); const [,startTransition]=useTransition();
  const router=useRouter(); const supabase=createClient();
  const emptyForm={nome:"",descricao:"",status:"ativo" as ProjetoStatus,dominio:"" as DominioEvolutivo|"",meta:"",progresso:0,cor:PROJETO_CORES[0]};
  const [form,setForm]=useState(emptyForm);
  function startEdit(proj:Projeto){setForm({nome:proj.nome,descricao:proj.descricao??"",status:proj.status,dominio:proj.dominio??"",meta:proj.meta??"",progresso:proj.progresso??0,cor:proj.cor??PROJETO_CORES[0]});setEditingId(proj.id);setShowForm(true);}
  function resetForm(){setForm(emptyForm);setShowForm(false);setEditingId(null);}
  async function handleSubmit(e:React.FormEvent){e.preventDefault();setLoading(true);const {data:{user}}=await supabase.auth.getUser();const payload={...form,dominio:form.dominio||null,meta:form.meta||null,descricao:form.descricao||null};if(editingId){await supabase.from("projetos").update(payload).eq("id",editingId);}else{await supabase.from("projetos").insert({...payload,user_id:user!.id});}resetForm();startTransition(()=>router.refresh());setLoading(false);}
  async function handleDelete(id:string){await supabase.from("projetos").delete().eq("id",id);startTransition(()=>router.refresh());}
  async function handleStatusChange(id:string,status:ProjetoStatus){await supabase.from("projetos").update({status}).eq("id",id);startTransition(()=>router.refresh());}
  const projetosAtivos=projetos.filter(p=>p.status==="ativo");
  const projetosOutros=projetos.filter(p=>p.status!=="ativo");
  return (
    <div className="p-4 md:p-8 max-w-3xl mx-auto page-enter">
      <div className="flex items-center justify-between mb-6"><div><h1 className="text-xl font-bold text-white flex items-center gap-2"><FolderKanban size={18} className="text-emerald-400"/>Projetos</h1><p className="text-zinc-500 text-sm mt-0.5">{projetos.length} projetos</p></div><button onClick={()=>setShowForm(true)} className="btn-primary flex items-center gap-1.5"><Plus size={15}/>Novo projeto</button></div>
      {projetos.length===0&&<div className="card p-10 text-center"><FolderKanban size={32} className="text-zinc-700 mx-auto mb-3"/><p className="text-zinc-500">Nenhum projeto ainda.</p><button onClick={()=>setShowForm(true)} className="btn-primary mt-4 inline-flex items-center gap-1.5"><Plus size={14}/>Criar projeto</button></div>}
      {projetosAtivos.length>0&&<div className="mb-6"><p className="text-xs font-medium text-zinc-600 uppercase tracking-wider mb-3">Ativos</p><div className="space-y-3">{projetosAtivos.map(proj=>(<ProjetoCard key={proj.id} proj={proj} eventCount={eventosCount[proj.id]??0} onEdit={()=>startEdit(proj)} onDelete={()=>handleDelete(proj.id)} onStatusChange={s=>handleStatusChange(proj.id,s)}/>))}</div></div>}
      {projetosOutros.length>0&&<div><p className="text-xs font-medium text-zinc-600 uppercase tracking-wider mb-3">Outros</p><div className="space-y-3">{projetosOutros.map(proj=>(<ProjetoCard key={proj.id} proj={proj} eventCount={eventosCount[proj.id]??0} onEdit={()=>startEdit(proj)} onDelete={()=>handleDelete(proj.id)} onStatusChange={s=>handleStatusChange(proj.id,s)}/>))}</div></div>}
      {showForm&&(<div className="fixed inset-0 z-50 flex items-end md:items-center justify-center p-4 bg-black/60 backdrop-blur-sm"><div className="card w-full max-w-lg max-h-[90vh] overflow-y-auto animate-slide-up"><div className="flex items-center justify-between p-5 border-b border-[rgba(99,113,242,0.1)]"><h2 className="text-sm font-semibold text-white">{editingId?"Editar projeto":"Novo projeto"}</h2><button onClick={resetForm} className="btn-ghost p-1"><X size={16}/></button></div><form onSubmit={handleSubmit} className="p-5 space-y-4"><div><label className="label">Nome *</label><input className="input" placeholder="Nome do projeto" required value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></div><div><label className="label">Descrição</label><textarea className="input min-h-[70px] resize-none" placeholder="O que é este projeto?" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></div><div><label className="label">Meta / objetivo</label><input className="input" placeholder="Qual o objetivo final?" value={form.meta} onChange={e=>setForm({...form,meta:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Status</label><select className="select" value={form.status} onChange={e=>setForm({...form,status:e.target.value as ProjetoStatus})}>{STATUS_LIST.map(s=><option key={s} value={s}>{PROJETO_STATUS_LABELS[s]}</option>)}</select></div><div><label className="label">Domínio</label><select className="select" value={form.dominio} onChange={e=>setForm({...form,dominio:e.target.value as DominioEvolutivo|""})}><option value="">Nenhum</option>{DOMINIOS.map(d=><option key={d} value={d}>{DOMINIO_LABELS[d]}</option>)}</select></div></div><div><label className="label">Progresso: {form.progresso}%</label><input type="range" min="0" max="100" value={form.progresso} onChange={e=>setForm({...form,progresso:Number(e.target.value)})} className="w-full accent-darwin-500"/></div><div><label className="label">Cor</label><div className="flex gap-2 flex-wrap">{PROJETO_CORES.map(cor=>(<button key={cor} type="button" onClick={()=>setForm({...form,cor})} className="w-7 h-7 rounded-full border-2 transition-all flex items-center justify-center" style={{backgroundColor:cor,borderColor:form.cor===cor?"white":"transparent"}}>{form.cor===cor&&<Check size={12} className="text-white"/>}</button>))}</div></div><div className="flex gap-2 pt-2"><button type="button" onClick={resetForm} className="btn-secondary flex-1">Cancelar</button><button type="submit" disabled={loading} className="btn-primary flex-1 disabled:opacity-50">{loading?"Salvando...":editingId?"Salvar":"Criar"}</button></div></form></div></div>)}
    </div>
  );
}
function ProjetoCard({proj,eventCount,onEdit,onDelete,onStatusChange}:{proj:Projeto;eventCount:number;onEdit:()=>void;onDelete:()=>void;onStatusChange:(s:ProjetoStatus)=>void;}){
  return(<div className="card-hover p-4 group"><div className="flex items-start gap-3"><div className="w-3 h-3 rounded-full flex-shrink-0 mt-1" style={{backgroundColor:proj.cor??"#6371f2"}}/><div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-sm font-semibold text-zinc-200">{proj.nome}</p>{proj.descricao&&<p className="text-xs text-zinc-600 mt-0.5 line-clamp-1">{proj.descricao}</p>}{proj.meta&&<p className="text-xs text-darwin-500/80 mt-0.5">🎯 {proj.meta}</p>}</div><div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-all flex-shrink-0"><button onClick={onEdit} className="btn-ghost p-1.5"><Edit2 size={13}/></button><button onClick={onDelete} className="btn-ghost p-1.5 hover:text-rose-400"><Trash2 size={13}/></button></div></div>{proj.progresso!==undefined&&proj.progresso>0&&<div className="mt-2"><div className="flex justify-between text-xs text-zinc-600 mb-1"><span>Progresso</span><span>{proj.progresso}%</span></div><div className="h-1 bg-zinc-800 rounded-full overflow-hidden"><div className="h-full rounded-full transition-all" style={{width:`${proj.progresso}%`,backgroundColor:proj.cor??"#6371f2"}}/></div></div>}<div className="flex items-center gap-2 flex-wrap mt-2"><span className={cn("badge text-xs",PROJETO_STATUS_CORES[proj.status])}>{PROJETO_STATUS_LABELS[proj.status]}</span>{proj.dominio&&<span className="text-xs text-zinc-600">{DOMINIO_LABELS[proj.dominio]}</span>}<span className="text-xs text-zinc-700">{eventCount} eventos</span><span className="text-xs text-zinc-700 ml-auto">{format(new Date(proj.created_at),"dd MMM yyyy",{locale:ptBR})}</span></div><div className="flex gap-1 mt-2">{(["ativo","pausado","concluido"] as ProjetoStatus[]).filter(s=>s!==proj.status).map(s=>(<button key={s} onClick={()=>onStatusChange(s)} className="text-xs text-zinc-700 hover:text-zinc-400 transition-colors">→ {PROJETO_STATUS_LABELS[s]}</button>))}</div></div></div></div>);
}